-- Ensure buses table exists
CREATE TABLE IF NOT EXISTS buses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number TEXT UNIQUE NOT NULL,
    route TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Delete existing data to avoid conflicts
DELETE FROM buses WHERE bus_number LIKE 'TS07EP092%';

-- Insert buses again
INSERT INTO buses (bus_number, route) VALUES
    ('TS07EP0921', 'LB Nagar - KMCE'),
    ('TS07EP0922', 'Secunderabad - KMCE'),
    ('TS07EP0923', 'Kukatpally - KMCE'),
    ('TS07EP0924', 'Uppal - KMCE'),
    ('TS07EP0925', 'Mehdipatnam - KMCE')
ON CONFLICT (bus_number) DO UPDATE 
SET route = EXCLUDED.route; 